
spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://sathishproject-config-server.eastus.azurecontainer.io:8888/}
  application:
    name: witraffic-url
  devtools:
    livereload:
      port: 35760
  cloud:
    config:
      uri: http://sathishproject-config-server.eastus.azurecontainer.io:8888
      profile: dev
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: embedded
      continue-on-error: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
server:
  port: 8085
