spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  application:
    name: witraffic-url
  devtools:
    livereload:
      port: 35760
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev

