DROP TABLE resume_user_profile IF EXISTS;
DROP TABLE security_user IF EXISTS;


CREATE TABLE security_user
(
    id        INTEGER IDENTITY PRIMARY KEY,
    user_name VARCHAR(30),
    password  VARCHAR(30),
    active    BOOLEAN,
    roles     VARCHAR(20)
);
CREATE INDEX security_user_user_name ON security_user (user_name);

CREATE TABLE TRAFFIC_ROAD_DATA
(
    ID           INTEGER IDENTITY PRIMARY KEYT,
    CURRENT_TIME FLOAT,
    DELAY        FLOAT,
    DESCRIPTION  VARCHAR(255),
    DISTANCE     FLOAT,
    NORMAL_TIME  FLOAT,
    REGIONL      VARCHAR(255),
    ROADWAY_NAME VARCHAR(255)
)
CREATE INDEX TRAFFIC_ROAD_DATA_DESCRIPTION ON TRAFFIC_ROAD_DATA (DESCRIPTION);
