spring:
  application:
    name: witraffic-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sathishjayapal/witraffic/tree/main/jubilant-memory
server:
  port: 8888
