spring:
  application:
    name: witraffic-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sathishjayapal/jubilant-memory
      profile: dev

server:
  port: 8888
